### ISSUE TITLE
Grayscale timelapses, four classes

### ISSUE THREAD

**Issue by cjh9** [haofanwang/video-swin-transformer-pytorch#2]
Hi!

I'm a researcher planning to use this to classify time-lapse of biomedical data. Would it be possible to use this with grayscale images. How can I adjust the pretrained weights for that? I see I can change `in_chans`.

Is `embed_dim` the number of classes?

**Comment by haofanwang** [comment]
For 2D images, I suggest you try swin transformer which has been adopted in many 2D tasks including classification.
