### ISSUE TITLE
为什么我运行代码显示没有backbone

### ISSUE THREAD

**Issue by z369437558** [haofanwang/video-swin-transformer-pytorch#5]

**Comment by haofanwang** [comment]
如果是需要跑`example.py`中的例子，需要参考官方代码，加载预训练模型。

https://github.com/haofanwang/video-swin-transformer-pytorch/blob/5fe99cace764ecc9ecfe660dc78b69d879e3b7ba/example.py#L31

**Comment by DWCTOD** [comment]
你好,遇到了同样的问题

**Comment by DWCTOD** [comment]
`# project
batch_size, hidden_dim = feat.shape
feat_dim = 512
proj = nn.Parameter(torch.randn(hidden_dim, feat_dim))

# final output
output = feat @ proj # [batch_size, feat_dim]`
你好,感觉这样子输出的结果怪怪的,一个视频的输入每次输出的结果都是随机的...
