### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by wutongshu819274135** [haofanwang/video-swin-transformer-pytorch#6]
提供的代码是不全的吗，没有看到可以运行例子的代码啊

**Comment by haofanwang** [comment]
运行example.py需要参考代码中的注释，下载官方代码的权重文件

**Comment by wutongshu819274135** [comment]
Example.py里面没有main函数，我看到注释里面说是不是要把这些文件全部放入官方video swin里面吗？之后我就没怎么看懂了，求大神解答一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Haofan Wang ***@***.***&gt;
发送时间: 2022年1月3日 00:13
收件人: haofanwang/video-swin-transformer-pytorch ***@***.***&gt;
抄送: wutongshu819274135 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [haofanwang/video-swin-transformer-pytorch] 运行问题 (Issue #6)





 
运行example.py需要参考代码中的注释，下载官方代码的权重文件
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haofanwang** [comment]
@wutongshu819274135 

example.py里是提供了两种加载模型的方式。一种是直接初始化，主要是把核心代码抽离出来，方便理解模型结构，这种方式直接执行即可；另一种就是官方机遇mmaction封装的方式，需要按照官方repo的要求进行配置环境后，把example.py拷贝到官方目录下，即可执行。

**Comment by wutongshu819274135** [comment]
那直接抽取出来是不是就不能使用预训练权重了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Haofan Wang ***@***.***&gt;
发送时间: 2022年1月3日 21:33
收件人: haofanwang/video-swin-transformer-pytorch ***@***.***&gt;
抄送: wutongshu819274135 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [haofanwang/video-swin-transformer-pytorch] 运行问题 (Issue #6)

**Comment by haofanwang** [comment]
我已经在README.md中更新了一种加载权重的方式，可以作为参考。但正式使用，仍然建议使用官方代码。

**Comment by haofanwang** [comment]
Solved.
